### PR TITLE
Added duplicate_char_counter.py

### PR DESCRIPTION
**Pull request by GoodbyeBlues**
An expansion of a CodeWars problem, with lots of detailed comments.

### CODE REVIEW

**Review by redcreeper14385 — CHANGES_REQUESTED** [review]
Python is fine, but you need to remove settings.json

**Comment by GoodbyeBlues** [comment]
Gotcha.

**Comment by GoodbyeBlues** [comment]
All good?

**Review by redcreeper14385 — APPROVED** [review]
All good!

**Pull request merged**
