### PR TITLE
Create merge_strings

### PR DESCRIPTION
**Pull request by Aditya060**
A simple java program to merge two user input strings.

### CODE REVIEW

**Review by redcreeper14385 — CHANGES_REQUESTED** [review]
Two things:
- Please name the file with the .java extension so it runs properly
- Please put the file in the Java folder.

Thanks!

**Comment by redcreeper14385** [comment]
@Aditya060 Please can you check the requested changes?

**Comment by redcreeper14385** [comment]
@Aditya060 They both need to be in the Java folder... :P

**Comment by Aditya060** [comment]
Done 1

**Comment by redcreeper14385** [comment]
They don't seem to be...

**Comment by Aditya060** [comment]
Resolved the comments.

**Pull request merged**
