### PR TITLE
Python/patterns.python

### PR DESCRIPTION
**Pull request by Rishika-crypto**
Created a file explaining basics of pattern printing which beginners (such as myself) find difficult.

### CODE REVIEW

**Review by redcreeper14385 — CHANGES_REQUESTED** [review]
If possible, could you change the file format to `.py` as GitHub doesn't seem to highlight `.python` files.

**Comment by redcreeper14385** [comment]
I'm aware that .python is equally valid but it doesn't seem to highlight

**Comment by Rishika-crypto** [comment]
I have made the necessary changes kindly check.
- Rishika

**Comment by redcreeper14385** [comment]
Thanks!

**Review by redcreeper14385 — APPROVED** [review]
All good!

**Comment by Rishika-crypto** [comment]
Thank you so much !
- Rishika

**Pull request merged**
