### PR TITLE
Add basic implementation of binary trees in Python3

### PR DESCRIPTION
**Pull request by AkashCherukuri**

### CODE REVIEW

**Comment by AkashCherukuri** [comment]
## Suggestion
I've noticed that the folders have too many files in them, which would make it tough for a beginner to go through everything, so I was thinking maybe I/you could partition the files into different folders, like; `data_structure_implementation`, `basic_problems`, or something like that. You could tell me to do it, and I'll make a PR which organizes stuff and adds a couple of new ones from my end too.

**Comment by AkashCherukuri** [comment]
## Requesting for Permission (..?)
Also, if its okay with you, I could add a C++ folder and maybe write some code regarding pointers, cause iirc I had a lot of trouble understanding them.

**Comment by redcreeper14385** [comment]
@AkashCherukuri feel free to do both of these, I would also appreciate if you:
- made all the files either snake case or, if it is java then `LikeThis`
- fixed any folder issues (i.e. things in wrong folder, duplicate folders, folders not in lower case)
This would be really appreciated, thanks!

**Comment by redcreeper14385** [comment]
@AkashCherukuri feel free to do both of these, I would also appreciate if you:
- made all the files either snake case or, if it is java then `LikeThis`
- fixed any folder issues (i.e. things in wrong folder, duplicate folders, folders not in lower case)
This would be really appreciated, thanks!

**Comment by redcreeper14385** [comment]
Oops double message there lol

**Comment by redcreeper14385** [comment]
Note: the stuff above is only if you want to do the organisation stuff

**Pull request merged**
