### PR TITLE
Create Java folder and Basic programs

### PR DESCRIPTION
**Pull request by saurabh-daware**

### CODE REVIEW

**Review by redcreeper14385 — CHANGES_REQUESTED** [review]
Would it be possible to rename the folder to `java`, lowercase?

**Comment by saurabh-daware** [comment]
Okay.

**Review by redcreeper14385 — APPROVED** [review]
All good!

**Comment by redcreeper14385** [comment]
Thanks!

**Comment by saurabh-daware** [comment]
**Thank you!**

**Pull request merged**
