### PR TITLE
Added sortings for Java & JavaScript files

### PR DESCRIPTION
**Pull request by jojobudiman**
Added the following files below for a better code land! 🚀 🎆 😊 :

Most of them are sorting files! 👀 

### InsertionSort.java
<br><br>
### selectionSort.js

### CODE REVIEW

**Review by redcreeper14385 — CHANGES_REQUESTED** [review]
Mind changing the file names to `camel_case` for consistency?

**Comment by jojobudiman** [comment]
Sure! Will do 👍

**Comment by redcreeper14385** [comment]
Thanks!

**Comment by jojobudiman** [comment]
No worries! Lmk if there are any consistency problems! 👍

**Pull request merged**
