### PR TITLE
Create number-pyraimid.java

### PR DESCRIPTION
**Pull request by ChandanaVKumar**
Hey! I'm Chandana V Kumar. I have created a simple program to print a number pyramid of natural numbers that progressively grows according to the number of rows given as input.

### CODE REVIEW

**Review by redcreeper14385 — CHANGES_REQUESTED** [review]
Looks good, mind renaming it to `number_pyramid` so it matches the naming conventions and is also spelled correctly?

**Comment by ChandanaVKumar** [comment]
Yes, of course. I'm sorry, will do it right away.

**Review by redcreeper14385 — APPROVED** [review]
Perfect, thanks!

**Comment by ChandanaVKumar** [comment]
Thank you!

**Pull request merged**
