### PR TITLE
Add pointer code and file organization

### PR DESCRIPTION
**Pull request by AkashCherukuri**
## Edits made
- I've partitioned `python`, `java`, `c` and `bash` folders appropriately. Better naming of the folders might be required imo.
- Created a new folder `c++` and added `pointers.cpp`, which explains the basic usage of pointers.
- Changed naming of all folders to lowercase, and all files have been named in camel_case (except Java, which has been named as you wanted it to be)

## What I didn't do
- I'd initially thought of putting the code related to database management (like `sql`) in a seperate folder altogether, but decided against it as it still is _technically_ `python`

### CODE REVIEW

**Comment by AkashCherukuri** [comment]
The naming of folders isn't the best, but it was the best i could come up with at the moment lol

**Comment by AkashCherukuri** [comment]
Maybe you could close [issue#36](https://github.com/redcreeper14385/the-code-land/issues/36) as well

**Comment by redcreeper14385** [comment]
Really well done, thank you so much!

**Comment by AkashCherukuri** [comment]
@redcreeper14385 :D

**Pull request merged**
